-- Question 9 - 12

CREATE TABLE EMPLOYEE(
    E_ID VARCHAR2(3),
    NAME VARCHAR2(20),
    PH_NO VARCHAR2(10)
);

INSERT INTO EMPLOYEE VALUES(
    '1',
    'Abhay',
    '1234567890'
);

INSERT INTO EMPLOYEE VALUES(
    '31',
    'Harsh',
    '1234567890'
);

INSERT INTO EMPLOYEE VALUES(
    '74',
    'Pandey',
    '1234567890'
);

ALTER TABLE EMPLOYEE ADD DESIGNATION VARCHAR2(20);

UPDATE EMPLOYEE
SET
    DESIGNATION = 'CTO'
WHERE
    E_ID = '1';

UPDATE EMPLOYEE
SET
    DESIGNATION = 'CEO'
WHERE
    E_ID = '31';

UPDATE EMPLOYEE
SET
    DESIGNATION = 'CFO'
WHERE
    E_ID = '74';

DELETE FROM EMPLOYEE
WHERE
    NAME = 'Abhay'
    AND DESIGNATION = 'CTO';

UPDATE EMPLOYEE
SET
    E_ID = E_ID + 100;